# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mivariableglobal: 'hola, soy una variable global'
    project_root: '%kernel.project_dir%'
    uploads-dir: '%kernel.project_dir%/public/uploads'
    imgs-dir: '%kernel.project_dir%/public/uploads/images'
    userImgDir: '/uploads/images'
    routeImgDir: '%kernel.project_dir%/public/images/route'
    routeImgDirDB: '/images/route'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\MessageGenerator:
        arguments:
            $adminEmail: 'admin@gmail.es'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # servicios para eventos
    # App\EventSubscriber\DoctrineEventSubscriber:
    # App\EventListener\DoctrineEventListener:
    #         arguments:
    #             # $mailer: '@Symfony\Component\Mailer\MailerInterface'
    #         tags:
    #             - { name: doctrine.event_listener, event: 'prePersist' }
    #             - { name: doctrine.event_listener, event: 'postPersist' }
    #             - { name: doctrine.event_listener, event: 'postUpdate' }
                # - { name: doctrine.event_listener, event: 'postRemove' }

                # - { name: doctrine.event_subscriber, event: 'prePersist' }
                # - { name: doctrine.event_subscriber, event: 'postPersist' }
                # - { name: doctrine.event_subscriber, event: 'postUpdate' }
                # - { name: doctrine.event_subscriber, event: 'postRemove' }

                # - { name: 'doctrine.orm.entity_listener', event: 'postPersist', entity: 'App\Entity\User' }
                # - { name: 'doctrine.orm.entity_listener', event: 'postPersist', entity: 'App\EventSubscriber' }
                # - { name: 'doctrine.orm.entity_listener', entity: 'App\Entity\User' }
                # - { name: 'doctrine.orm.entity_listener', event: 'postPersist' }
                # - { name: 'doctrine.orm.entity_listener' }
                # - { name: 'kernel.event_subscriber' }
                #  - { name: doctrine.orm.entity_listener' }
                # - { entity: 'App\Entity\User' } 